version: "3.8"

services:
  app:
    build: .
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: prometheus
      POSTGRES_PASSWORD: prometheus
      POSTGRES_DB: prometheus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

